
// This file is autogenerated.
// It was added by catch_registerstaticlibrary.cmake in order to ensure that the tests are properly run by catch.
// Please commit it if needed, it will be modified only if new files are added.

int catchRegister_781f5131_2d32_4cd8_92cf_d83b7f4fcd20();
int catchRegister_d040fbb6_21b9_4865_8de0_c05702d9ae1e();


int CatchRegisterStaticLibrary()
{
  int dummy_sum = 0;
  dummy_sum += catchRegister_781f5131_2d32_4cd8_92cf_d83b7f4fcd20();
  dummy_sum += catchRegister_d040fbb6_21b9_4865_8de0_c05702d9ae1e();

  return dummy_sum;
}
