
// This file is autogenerated.
// It was added by rsl_registerstaticlibrary.cmake in order to ensure that the tests are properly run.
// Please commit it if needed, it will be modified only if new files are added.

int RslRegister_c774c3c1_ae12_4c4c_9faa_93c8a7140a5c();
int RslRegister_585e2fbf_a17b_46a2_887a_093a38c17173();


int RslRegisterStaticLibrary()
{
  int dummy_sum = 0;
  dummy_sum += RslRegister_c774c3c1_ae12_4c4c_9faa_93c8a7140a5c();
  dummy_sum += RslRegister_585e2fbf_a17b_46a2_887a_093a38c17173();

  return dummy_sum;
}
