#!/bin/python
import sys
import uuid
import os.path
import re

def findWholeWord_Regex(w):
    return re.compile(r'\b({0})\b'.format(w)).search

FileCode = """
// This code was added by catch_registerstaticlibrary.cmake in order to ensure that the tests are properly run by catch.
// Please commit it if needed, it will be added only once, and never modified.
// Before committing, you can remove this comment, as long as you leave the function below.
int catchRegister_GUID() { return 0; }
"""

catchRegisterCppCode = """
// This file is autogenerated.
// It was added by catch_registerstaticlibrary.cmake in order to ensure that the tests are properly run by catch.
// Please commit it if needed, it will be modified only if new files are added.

[DeclareRegisterFunctions]

int CatchRegisterStaticLibrary()
{
  int dummy_sum = 0;
[CallRegisterFunctions]
  return dummy_sum;
}
"""
allowedExtensions = ["cpp", "cc", "cxx"]

# words that indicate that a file actually uses catch
catch_usage_hints = ["catch.hpp", "TEST_CASE", "SCENARIO"]


def DoesSourceFileUsecatch(lines):
    doesFileUsecatch = False
    for line in lines:
        line=line[:-1]
        # print("testing line ==>" + line + "<==")
        for catch_usage_hint in catch_usage_hints:
            my_regex = findWholeWord_Regex(catch_usage_hint)
            if (my_regex(line)):
                doesFileUsecatch = True
                # print("Match with " + catch_usage_hint)
        if (doesFileUsecatch):
            break
    print("doesFileUsecatch=" + str(doesFileUsecatch))
    return doesFileUsecatch

def ProcessFile(filename):
    # print("ProcessFile " + filename)
    if (filename == "catch_registerstaticlibrary.cpp"):
        return

    file_extension = filename.split(".")[-1]
    if not file_extension in allowedExtensions:
        return

    with open(filename, 'r') as f:
        lines = f.readlines()

    if not DoesSourceFileUsecatch(lines):
        return

    tokenPresent = False
    for line in lines:
        if ("int catchRegister_" in line):
            tokenPresent = True

    if (not tokenPresent) :
        id = str(uuid.uuid4()).replace("-", "_")
        with open(filename, 'a') as f:
            codeWithUuid = FileCode.replace("GUID", id)
            f.write(codeWithUuid)
            print(filename + " was modified (added catchRegister_ function()")


def RegisterCppFiles(sourceFiles):
    for filename in sourceFiles:
        ProcessFile(filename)

def RegisterMainFile(sourcesFiles):
    #print("ProcessLibrary ")
    guidList = []
    for filename in sourcesFiles:
        file_extension = filename.split(".")[-1]
        if not file_extension in allowedExtensions:
            continue

        guid = ""
        with open(filename, 'r') as f:
            lines = f.readlines()
        for line in lines:
            if ("int catchRegister_" in line):
                line = line.replace("int", "").replace("(", "").replace(")", "")
                words = line.split()
                for word in words:
                    if ("catchRegister_" in word):
                        guid = word.replace("catchRegister_", "")
        if (guid != ""):
            guidList.append(guid)

    declareRegisterFunctionsCode = ""
    callRegisterFunctionsCode = ""
    for guid in guidList:
        declareRegisterFunctionsCode = declareRegisterFunctionsCode + "int catchRegister_" + guid + "();\n"
        callRegisterFunctionsCode = callRegisterFunctionsCode + "  dummy_sum += catchRegister_" + guid + "();\n";

    codeWithGuidList = catchRegisterCppCode
    codeWithGuidList = codeWithGuidList.replace("[DeclareRegisterFunctions]", declareRegisterFunctionsCode)
    codeWithGuidList = codeWithGuidList.replace("[CallRegisterFunctions]", callRegisterFunctionsCode)
    #print(codeWithGuidList)

    if (not os.path.isfile("catch_registerstaticlibrary.cpp") ):
        print("catch_registerstaticlibrary.cpp was created (you can add it to source control, or ignore it, as preferred)")
    with open("catch_registerstaticlibrary.cpp", "w") as f:
        f.write(codeWithGuidList)



def help():
    helpMessage = """
        Usage :
            _command_ -registercppfiles file1.cpp file2.cpp ...
                Will add a catchRegister_GUID() to cpp files
            _command_ -registermainfile file1.cpp file2.cpp file3.cpp ...
                Will create a catch_registerstaticlibrary.cpp file with one function that calls all catchRegister_GUID() functions
    """
    helpMessage = helpMessage.replace("_command_", sys.argv[0])
    print(helpMessage)

def main():
    if (len(sys.argv) < 2):
        help()
        exit(1)
    if (sys.argv[1] == "-registercppfiles"):
        files = sys.argv[2:]
        RegisterCppFiles(files)
    elif (sys.argv[1] == "-registermainfile"):
        files = sys.argv[2:]
        RegisterMainFile(files)
    else:
        help()

main()
